version: "3.8"

services:
  db-administrativo:
    image: mariadb:10.7.1
    restart: always
    container_name: db-administrativo
    environment:
      MARIADB_ROOT_PASSWORD: $DB_ADMINISTRATIVO_ROOT_PASSWORD
    volumes:
      - ./data/administrativo/mariadb:/var/lib/mysql
      - ./scripts/init-db-administrativo/init-db.sh:/docker-entrypoint-initdb.d/init.sh
      - ./scripts/init-db-administrativo/template.sql:/docker-entrypoint-initdb.d/template
    ports:
      - "$DB_ADMINISTRATIVO_PORT:3306"

  db-materia:
    image: mongo:5.0.3
    container_name: db-materia
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $DB_MATERIA_ROOT_PASSWORD
    volumes:
      - ./data/matéria/mongodb:/data/db
    ports:
      - "$DB_MATERIA_PORT:27017"
