version: "3.8"

services:
  db-administrativo:
    image: mariadb:10.7.1
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    volumes:
      - ./data/administrativo/mariadb:/var/lib/mysql
    ports:
      - "$DB_ADMINISTRATIVO_PORT:3306"

  db-materia:
    image: mongo:5.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_USER_ROOT_PASSWORD
    volumes:
      - ./data/matéria/mongodb:/data/db
    ports:
      - "$DB_MATERIA_PORT:27017"
