name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_ADMINISTRATIVO_ROOT_PASSWORD: ${{ secrets.DB_ADMINISTRATIVO_ROOT_PASSWORD }}
      DB_MATERIA_ROOT_PASSWORD: ${{ secrets.DB_MATERIA_ROOT_PASSWORD }}
      DB_ADMINISTRATIVO_PORT: 7000
      DB_MATERIA_PORT: 7001
      BACKEND_PORT: 8000
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    services:
      db-administrativo:
        image: mariadb:10.7.1
        env:
          MARIADB_ROOT_PASSWORD: $DB_ADMINISTRATIVO_ROOT_PASSWORD
        options: >-
          -v ./data/administrativo/mariadb:/var/lib/mysql
          -v ./scripts/init-db-administrativo/init-db.sh:/docker-entrypoint-initdb.d/init.sh
          -v ./scripts/init-db-administrativo/template.sql:/docker-entrypoint-initdb.d/template
        ports:
          - $DB_ADMINISTRATIVO_PORT:3306

      db-materia:
        image: mongo:5.0.3
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: $DB_MATERIA_ROOT_PASSWORD
        options: >-
          -v ./data/matéria/mongodb:/data/db
          -v ./scripts/init-db-matéria/init.js:/docker-entrypoint-initdb.d/init.js
        ports:
          - $DB_MATERIA_PORT:27017

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Verificando containers
        run: docker ps
      - name: Verificando hosts
        run:  cat /etc/hosts
      - name: Rodando Corbetura De Código
        run: cd backend && go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Enviando Corbetura De Código Para Codecov
        run: cd backend && bash <(curl -s https://codecov.io/bash)
