name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_ADMINISTRATIVO_ROOT_PASSWORD: ${{ secrets.DB_ADMINISTRATIVO_ROOT_PASSWORD }}
      DB_MATERIA_ROOT_PASSWORD: ${{ secrets.DB_MATERIA_ROOT_PASSWORD }}
      DB_ADMINISTRATIVO_PORT: 7000
      DB_MATERIA_PORT: 7001
      BACKEND_PORT: 8000
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Subindo Os Bancos De Dados Necessários Para Rodar Os Testes
        run: docker-compose up -d  db-materia db-administrativo
      - name: Verificando containers
        run: docker ps
      - name: Rodando Corbetura De Código
        run: cd backend && go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Enviando Corbetura De Código Para Codecov
        run: cd backend && bash <(curl -s https://codecov.io/bash)
